# -*- coding: utf-8 -*-
"""projects_budget_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NInzA2NckN56aTuRsxyhLpFTqHQz53-x
"""

import pandas as pd
import numpy as np
import tensorflow as tf

from flask import Flask, request, jsonify
from joblib import load
from tensorflow import keras

path = r"C:\Users\DELL\karira\projects_budget\budget_label_model\my_model"
budget_label_model = tf.keras.models.load_model(path)

app = Flask(__name__)

@app.route("/predict", methods=["POST"])

def vocab():
  vocab = []
  with open(r'C:\Users\DELL\karira\projects_budget\projects_budget_vocab.txt', 'r') as fp:
    for line in fp:
      x = line[:-1]
      vocab.append(x) 
  return vocab

def predict():
    """Takes a POST request with a key of \"text\" and the text to be classified."""
    data_dict = request.get_json()
    text = [data_dict["text"]]
    user_input = pd.Series(str(text))
    predicted_probabilities = budget_label_model(user_input)
    for i, text in enumerate(user_input):
    print(f"Text: {text}")
    prediction = sorted(zip(predicted_probabilities[i], vocab()),
                        key=lambda pair: pair[0],
                        reverse=True)
    top_1 = prediction[0][1] 
    output = [top_1]
    return jsonify({"result": output})